package shape

import (
	"encoding/json"
	"testing"
)

// leakCorpus is every command line an adversarial review found to put data --
// an argument, a redirect target, a here-document or here-string word, an
// assignment value, an array element, an arithmetic operand, a fragment of a
// word the tokenizer split -- into the program field. The first 165 came from
// a review of the second version of the program search (54 of them leaked on
// main as well); the rest from a review of the third. Each is checked by a parser only; none is ever run.
var leakCorpus = []string{
	"\"$(< /etc/passwd)\"",
	"\"$(cat /etc/passwd)\"",
	"\"$(cat /home/alice/secret-path)\" --flag",
	"\"$(cat <<EOF\nhunter2\nEOF\n)\"",
	"\"$(echo $((a/b)))\"",
	"\"$(echo hello world)\"",
	"\"${(f)$(cat /a/b)}\"",
	"&& \"$(cat /x/y)\"",
	"&& arr[1 + 1]=x ls",
	"&>! /home/alice/secret.csv ls",
	"&>! file cmd",
	"&>>! log.txt echo hi",
	"( \"$(cat /x/secret-path)\" )",
	"( $[a/b] )",
	"( <<< ${x:-a b} cat )",
	"( >! out.log make )",
	"( X=\"$(echo \"a b\")\" ls )",
	"( arr[customer acme]=1 ls )",
	"( deploy_acme() { ls; }; deploy_acme )",
	"( n=$[a + b] )",
	"(2>&1 cmd)",
	"(arr[i==0]=v ls)",
	"(arr[k=/home/alice/x]=v ls)",
	"0<<<secret cat",
	"0<<EOF\nsecret body\nEOF",
	"10>log.txt cmd",
	"1>&2 echo error",
	"2>/dev/null ls",
	"2>/dev/null ls -la",
	"3<<<\"secret text\" cmd",
	"; \"$[a/b]\"",
	"; x=$'a\\' b c'",
	"< ${INPUT:?missing input file} cat",
	"< in \"$(cat /home/alice/secret.csv)\"",
	"<<< \"$(<\"/home/alice/My file.txt\")\" cat",
	"<<< \"$(cat \"a b\")\" grep y",
	"<<< \"$(echo \"a b\")\" cat",
	"<<< \"$(jq -r \".name\" \"/data/customer list.json\")\" xargs echo",
	"<<< $'don\\'t ; secret \"' cat",
	"<<< $'don\\'t SECRET here' cat",
	"<<< $[x * 3] cmd",
	"<<< ${msg:-hello world} cat",
	"<<< ${x:-a b c d} cmd",
	"<<< `echo a SECRET` wc -w",
	"<<< `printf %s secret word` cat",
	"<<< a >&! /tmp/out cat",
	"<<< x >! out cmd",
	"<<<`echo a b c` cat",
	"<<<x 2>&1 cmd",
	"> !(x) cmd",
	"> \"$( echo \"; secret\" )\" ls",
	"> \"$(dirname \"$HOME/My Documents/x\")/out\" cat",
	"> \"$(printf \"%s %s\" SECRET TWO)\" ls",
	"> \"$OUT_DIR/$(date \"+%Y-%m-%d %H\")\".log ls",
	"> #SECRET comment text\nls",
	"> $'\\' ; secret \"'",
	"> $'it\\'s a file' ls",
	"> $[1 + 2] cmd",
	"> ${HOME:-/tmp dir}/out.log cmd",
	"> ${OUT:?OUT must be set} make",
	"> ${arr[i + 1]} cmd",
	"> ${f// /_} ls",
	"> ${x#* } cmd",
	"> ${x%% *} cmd",
	"> ${x// /_} cmd",
	"> ${x: -1} cmd",
	"> ${x:-$[1 + 2]} cmd",
	"> ${x:-a b} cmd",
	"> ${x:-a b}${y:-c d} cmd",
	"> *(.) cmd",
	"> *(N) cmd",
	"> **/*(.om[1]) cmd",
	"> +(x) cmd",
	"> /dev/null 2>&1 command -v jq",
	"> /tmp/`date +%s %N`.log ls",
	"> ?(x y) cmd",
	"> @(a|b) cmd",
	"> `echo a b` cmd",
	"> `printf %s a b` ls",
	"> a${b:-c d}e cmd",
	"> f 0<<EOF",
	"> f 3<<<x cmd",
	"> f arr[i==0]=v ls",
	"> f { secret",
	"> file(1).txt cmd",
	"> out\rsecret ls",
	"> out; a[1 + 1]=x",
	">! /home/alice/secret.csv ls",
	">! file cmd",
	">\"$(date \"+%Y %m\")\" ls",
	">#c secret",
	">$[ a ] cmd",
	">&! /home/alice/secret.csv ls",
	">&! file cmd",
	">&${fd:-a b} cmd",
	">/dev/null 2>&1 cmd",
	">/dev/null 2>&1 command -v git",
	">>! /home/alice/secret.csv ls",
	">>! file cmd",
	">>&! /home/alice/secret.csv ls",
	">>&! file cmd",
	">f {fd}>g cmd",
	">out 2>err ls",
	">| ${x:-a b} cmd",
	"A=1 >! out.log make",
	"A=1 >f 2>f B=2 cmd",
	"A=1 {fd}>x cmd",
	"BRANCH=\"$(git log -1 --format=\"%s by %an\")\"",
	"COUNT=\"$(grep -c \"customer acme\" /data/x.csv)\" && echo $COUNT",
	"FOO=bar\rbaz qux",
	"GH_TOKEN=\"$(security find-generic-password -a \"$USER\" -s \"gh token\" -w)\" gh pr list",
	"JSON=\"$(curl -s -H \"Authorization: Bearer $TOKEN\" https://api.example.com)\"",
	"LATEST=\"$(ls -t \"/Users/alice/My Drive\" | head -1)\"",
	"MSG=\"$(printf \"%s %s\" SECRETA SECRETB)\" git commit -m \"$MSG\"",
	"NAME=\"${1:-\"default secret name\"}\" ./run.sh",
	"OUT=\"$(go test ./... 2>&1 | grep -v \"no test files\")\"",
	"PID=\"$(pgrep -f \"node server\")\" && kill $PID",
	"TS=\"$(date \"+%Y%m%d %H%M%S\")\"",
	"VERSION=\"$(cat \"my file.txt\")\" make",
	"VERSION=\"$(jq -r \".version // \\\"0.0.0\\\"\" package.json)\" npm publish",
	"X+=\"$(echo \"a b\")\" ls",
	"X=\"${Y//\"a b\"/c}\" ls",
	"X=$'\\'' echo 'SECRET words here'",
	"X=${arr[a b]} ls",
	"a[$(echo 1)]=v",
	"a[1 + 1]=x",
	"arr[$((i+1))]=v ls",
	"arr[0]=x \"$(cat /x)\"",
	"arr[a b]=SECRET ls",
	"arr[i==0]=secretvalue ls",
	"deploy_customer_acme() { echo hi; }; deploy_customer_acme",
	"f() { rm -rf /; }",
	"n=$[ 1 + 2 ] ls",
	"out=\"$(git log --format=\"%H %s\")\"",
	"x=\"$( echo \"; secret\" )\"",
	"x=\"$(echo \";secret\")\"",
	"x=\"$(echo \"a b\")\"",
	"x=\"$(echo \"a;b\")\"",
	"x=\"${a[$(echo \"1 2\")]}\" ls",
	"x=\"${y:-\"a b\"}\"",
	"x=\"${y:-\"| b\"}\"",
	"x=$'a\\' ; secret \"'",
	"x=$'a\\' b c' ls",
	"x=$'a\\' { secret \"'",
	"x=$'a\\' | secret \"'",
	"x=${y% *}",
	"x=${y:-default value}",
	"x=1\rsecret",
	"x=1 \r secret",
	"x=1 && FOO=$'it\\'s ; rm -rf x \"'",
	"x=1 { secret",
	"x=1; y=\"$(git log --format=\"%H %s\")\"",
	"y=${x// /_}",
	"{ 2>&1 cmd; }",
	"{ 2>&1 make; } | tee /tmp/build.log",
	"{ >! /home/alice/secret.csv ls; }",
	"{ >out 2>err ls; }",
	"{ x=$'a\\' ; secret \"'; }",
	"{ x=${y:-a b}; }",
	"{ { arr[x=1]=secret ls; }; }",
	"{customerfd}</home/alice/in.csv cat",
	"{fd}>/tmp/x echo hi",
	"{fd}>out ls",
	"| \"$(( a / b ))\"",
	"|| \"${x:-$(cat /etc/shadow)}\"",
	// A third review, against the version that ended at opaque words.
	"caf\u00e9=/Users/alice/acme-merger ls",
	"1=/home/alice/secret-path ls",
	"a[1]'='v ls",
	"X=$\\\n'it\\'s SECRET here' ls",
	"<\\\n<EOF\nsecret body\nEOF",
	"<1-9> /home/alice/secret.csv cat",
	"deploy_acme deploy_prod () { ls; }",
	"<\\\n<EOF\nhunter2 password\nEOF",
	"<\\\n<EOF\n/home/alice/.ssh/id_rsa\nEOF",
	"<\\\n<'EOF'\nSECRETBODY line\nEOF",
	"<\\\n<-EOF\n\tSECRETBODY\nEOF",
	"<\\\n<\\\n-EOF\nSECRETBODY\nEOF",
	"> /tmp/out <\\\n<EOF\nSECRETBODY hunter2\nEOF",
	"DB_PASS=x <\\\n<EOF\nSECRETBODY\nEOF",
	"A=1 >f <\\\n<EOF\nSECRETBODY\nEOF",
	"( <\\\n<EOF\nSECRETBODY\nEOF\n)",
	"{ <\\\n<EOF\nSECRETBODY\nEOF\n}",
	"X=$\\\n{Y:-a b c} cmd",
	"MSG=$\\\n{M:-deploy acme corp now} git push",
	"X=$\\\n'it\\'s secret words' cmd",
	"X=$\\\n'a\\' SECRET b' cmd",
	"X=$\\\n[1 + 2] cmd",
	"X=$\\\n[ 4111111111111111 ] cmd",
	"X=$\\\n{a[i + 1 + j]} cmd",
	"> $\\\n{x:-a b c} cmd",
	"<<< $\\\n{x:-alpha SECRET gamma} cat",
	"<<< $\\\n'don\\'t SECRET here' cat",
	"> $\\\n'it\\'s a file' ls",
	"( X=$\\\n{Y:-a b c} cmd )",
	"{ X=$\\\n{Y:-a b c} cmd; }",
	"> (x) cmd",
	"> (a|b) cmd",
	"> (/home/alice/secret.csv) ls",
	"< (secret.csv) cat",
	">> (build.log) make",
	">| (SECRET) make",
	">|(out.log) make",
	"&> (SECRET) make",
	"&>(SECRET) make",
	">& (SECRET) make",
	">&(SECRET) make",
	"<> (SECRET) cat",
	"<>(SECRET) cat",
	"<<< (SECRET) cat",
	">>| (SECRET) make",
	"> <1-10> cmd SECRET",
	"> <-> cmd SECRET",
	"<-> cmd SECRET",
	"<1-5> x SECRET",
	"A=1 <1-9> file secret",
	"< <-> cmd SECRET",
	"><1-5> cmd SECRET",
	"> f<1-3> cmd SECRET",
	"<<< <-> cat SECRET",
	">> <10-> tee SECRET",
	"( <-> a SECRET )",
	"{ <-> a SECRET; }",
	"<-5> ls SECRET",
	"<1-> ls SECRET",
	"a[0\\]=v customer_acme_q3 --prod",
	"MAP[key']'=secretvalue deploy --prod",
	"a[0\"]\"=v cmd SECRET",
	"a[0\\]+=v cmd SECRET",
	">f a[0\\]=v cmd SECRET",
	"A=1 a[k\\]=v cmd SECRET",
	"< (config|settings).json jq -r .name",
	"< (customer-list).csv wc -l",
	"> (secret-report).txt cat",
	"&>(acme-debug).log make",
	">|(acme-out).log make",
	"<<<(hunter2) cat",
	"A=1 < (secret|other).csv sort",
	"caf\u00e9=/Users/alice/Documents/secret.pdf open \"$caf\u00e9\"",
	"pr\u00e9nom=Alice ./greet.sh",
	"stra\u00dfe=/private/acme-merger.docx ls",
	"1=/home/alice/customer-list.csv ls",
	"2=hunter2 cmd",
	"1+=/private/secret-suffix ls",
	"x=1 1=/tmp/q3-layoffs.txt ls",
	"a[x]\"=\"v secret-arg",
	"a[x]'='/home/alice/secret.csv SECRETWORD",
	"a[x]\\=v SECRETWORD",
	"a[x]+\\=v SECRETWORD",
	"m[k]\"=\"hunter2 /home/alice/secret.csv",
	"cfg[env]\\=prod deploy-acme",
	"a[x\\]=v SECRETWORD",
	"a[x\"]\"=v SECRETWORD",
	"< report-<-> wc -l",
	"> f<-> cmd SECRETARG",
	"x=<-> SECRETCMD arg",
	"arr[0]\"=\"x SECRET",
	"arr[0]\\=x SECRET",
	"arr[0]'='x SECRET",
	"arr[0]\"+\"=x SECRET",
	"arr[0]\\+=x SECRET",
	"arr[0\"[\"]]=x SECRET",
	"arr[0\\]=x SECRET",
	"arr[0\"]\"=x SECRET",
	"arr['0]=x' SECRET",
	// A fourth: a redirect at the end of a line, whose "target" was the next
	// line's command.
	">\nrm -rf /home/alice/secret-dir",
	"<\ncat /home/alice/secret.csv",
	">\nscp /home/alice/secret.csv host:",
	"<\nsort /home/alice/customer-list.csv",
	"<<<\nmysql -phunter2 prod",
	">>\nssh deploy@acme-prod.internal",
	"> \t \ncat acme-merger.txt",
	">&\n2 SECRETWORD",
	"( <<<\ngit push SECRETREMOTE )",
	">\ncurl -H secret-token https://x",
	"&& >\nrm -rf /srv/acme",
	"A=1 B=2 >\nrm -rf /srv/acme",
	">f >\nrm -rf /srv/acme",
	"{ <\ncat /home/alice/secret.csv; }",
	">\\\n\nrm -rf x",
	">\n'rm' -rf x",
	// Variants of programClaims (below): the same classes spelled with a
	// different byte or operator.
	"mysql\u00a0-phunter2\u00a0prod",
	"X=1 git\u00a0push\u00a0acme-secret",
	"'curl\u00a0-H\u00a0token:hunter2'",
	"ls\u00a0-la\u00a0/Users/alice/secret-dir",
	"cat\f/home/alice/secret.csv",
	"cat\x1f/home/alice/secret.csv",
	"cat\u2003/home/alice/secret.csv",
	"cat\u3000/home/alice/secret.csv",
	"cat\u2028/home/alice/secret.csv",
	"cat\u0085/home/alice/secret.csv",
	"<<\n<& secret-fd cmd",
	// A separator inside a group ending the search for (), a syntax error
	// read past, and words that can never name a program.
	"deploy_acme <(x; y) () { ls; }",
	"deploy_acme @(a|b) () { ls; }",
	"deploy_acme $(x; y) () { ls; }",
	"deploy_acme `x; y` () { ls; }",
	"deploy_acme > $(echo x; true) deploy_prod () { ls; }",
	"deploy_acme > | x deploy_prod () { ls; }",
	"> ; /home/alice/secret.csv x",
	"/home/alice/acme-q3/ --prod",
	"~hunter2",
	"/usr/bin/^SECRET",
	"'' SECRET",
	// A group whose depth the tokens do not show, a ${ the word does not
	// close, and quotes the lexer cannot vouch for reading as the shell
	// does: each hid the () after the command word.
	"f $$'\\' () { ls; } 'x'",
	"f $$'\\' () { ls; }'",
	"deploy_acme $$'\\' () { ls; }",
	"deploy_acme $(case x in a) :;; esac) () { ls; }",
	"deploy_acme $(# )\n) () { ls; }",
	"deploy_acme ${ x; y; } () { ls; }",
	"deploy_acme \"$(echo '\"')\" () { ls; }",
	"deploy_acme $(cat <<EOF\n)\nEOF\n) () { ls; }",
	// A redirect whose target is another redirect or a comment, and paths
	// ending in a directory, or a jobspec, in command position.
	"> > /home/alice/secret.csv SECRETARG",
	"> > x /home/alice/secret-thing",
	"> #hunter2 x",
	"/home/alice/acme-q3/.",
	"/home/alice/acme-q3/..",
	"%hunter2",
}

// programClaims are 183 lines for which a parse-only pass found Derive
// recording data as the program, each upheld by three skeptics; program is
// the value recorded. As with the corpus above, every line is only ever handed
// to the parser.
var programClaims = []struct{ in, program string }{
	// A process substitution glued to the command word. Bash and zsh both read
	// x<(...) and x>(...) as ONE word (x/dev/fd/63), so the piece before `<`
	// is a fragment of it.
	{"/home/alice/acme-merger<(true) --flag", "acme-merger"},
	{"/srv/customer-acme/bin<(true) arg", "bin"},
	{"./q3-layoffs<(echo x) run", "q3-layoffs"},
	{"/Users/alice/hunter2dir>(cat) x", "hunter2dir"},
	{"\"secret-name\"<(true) x", "secret-name"},
	{"'acme-corp'>(true) x", "acme-corp"},
	{"A=1 /home/alice/acme-merger<(true) --prod", "acme-merger"},
	{"> out.log /home/alice/acme-merger<(true) --prod", "acme-merger"},
	{"{ /home/alice/acme-merger<(true); }", "acme-merger"},
	{"( /home/alice/acme-merger<(true) )", "acme-merger"},
	{"&& /home/alice/acme-merger<(true)", "acme-merger"},
	{"diff<(sort a)<(sort b)", "diff"},
	{"tee>(gzip > out.gz) SECRETARG", "tee"},
	{"x\\\n<(y) z", "x"},

	// A zsh numeric glob, <n-m> or <->, glued inside the command word: to zsh it
	// is one glob word, and the piece before `<` is a fragment of it.
	{"/home/alice/acme-<1-3>/run.sh --prod", "acme-"},
	{"/Users/alice/customer-acme-q<1-4>/deploy --prod", "customer-acme-q"},
	{"./build-<1->/bin/tool arg", "build-"},
	{"/srv/secret-<-5>/x arg", "secret-"},
	{"\"acme\"<1-9> arg", "acme"},
	{"A=1 /home/alice/acme-<1-3>/run.sh", "acme-"},
	{"> f /home/alice/acme-<1-3>/run.sh", "acme-"},
	{"{ /home/alice/acme-<1-3>/run.sh; }", "acme-"},
	{"( /home/alice/acme-<1-3>/run.sh )", "acme-"},
	{"x<1-9> SECRET", "x"},
	{"cmd<-> arg", "cmd"},
	{"x<1-9>>out SECRET", "x"},
	{"x<1-9>|wc", "x"},

	// Redirect-operator pieces with a newline or a blank between them. `>&`
	// and `> &` are different programs: the second is a redirect with no
	// target and then a separator -- a syntax error in both shells.
	{">\n&2 SECRETWORD", "SECRETWORD"},
	{">\n| SECRETCMD secretarg", "secretarg"},
	{">\n|x hunter2", "hunter2"},
	{">>\n& 1 secret-arg", "secret-arg"},
	{"<\n& 0 hunter2", "hunter2"},
	{"<\n&0 cat /home/alice/secret.csv", "cat"},
	{"> & 2 SECRETARG", "SECRETARG"},
	{"> | x hunter2", "hunter2"},
	{"< & 0 hunter2", "hunter2"},
	{">> & 1 SECRETARG", "SECRETARG"},
	{">> | f SECRETARG", "SECRETARG"},
	{"A=1 > & 2 SECRETARG", "SECRETARG"},
	{"{ > & 2 SECRETARG; }", "SECRETARG"},
	{"( > | f SECRETARG )", "SECRETARG"},
	{"> & | f SECRETARG", "SECRETARG"},
	{">\n&\n| f SECRETARG", "SECRETARG"},
	{">& | f SECRETARG", "SECRETARG"},
	{"&> | f SECRETARG", "SECRETARG"},
	{"&>\n| f SECRETARG", "SECRETARG"},

	// A computed command word. zsh applies colon modifiers to an unbraced
	// parameter, so $x:gs/SECRET// runs $x with SECRET removed, and path.Base
	// read the substitution's `/` delimiters as a path.
	{"$x:gs/SECRET//", "SECRET"},
	{"$x:s/SECRET/", "SECRET"},
	{"$x:s/SECRET//", "SECRET"},
	{"$x:gs/hunter2//", "hunter2"},
	{"$x:gs/customer-acme//", "customer-acme"},
	{"$cmd:gs/hunter2// --prod", "hunter2"},
	{"\"$x:gs/SECRET//\"", "SECRET"},
	{"\"$x:gs/customer-acme//\" arg", "customer-acme"},
	{"\"$x:s/SECRET/\"", "SECRET"},
	{"$0:s/SECRET//", "SECRET"},
	{"$1:s/SECRET/", "SECRET"},
	{"$x:h:s/SECRET/", "SECRET"},
	{"$x:q:s/SECRET//", "SECRET"},
	{"$x:l:gs/SECRET//", "SECRET"},
	{"$~x:s/SECRET/", "SECRET"},
	{"$^x:s/SECRET/", "SECRET"},
	{"$x:s/SECRET b/", "SECRET"},
	{"$x:s/SECRET/&x", "SECRET"},
	{"$x:s/SECRET/;ls", "SECRET"},
	{"$x:s/SECRET/|cat", "SECRET"},
	{"$x:s/SECRET/>out", "SECRET"},
	{"$x:s/SECRET/<in", "SECRET"},
	{"$x:s/SECRET/&&ls", "SECRET"},
	{"$x:s/SECRET/\nls", "SECRET"},
	{">out $x:s/SECRET/", "SECRET"},
	{">f <g $x:gs/SECRET//", "SECRET"},
	{"<<< w $x:gs/SECRET//", "SECRET"},
	{"X=1 $x:s/SECRET/ arg", "SECRET"},
	{"A=1 B=2 $x:gs/SECRET//", "SECRET"},
	{"( $x:s/SECRET/ )", "SECRET"},
	{"{ $x:s/SECRET/; }", "SECRET"},
	{"&& $x:s/SECRET/", "SECRET"},
	{"; $x:gs/SECRET//", "SECRET"},
	{"| $x:gs/SECRET//", "SECRET"},
	{"$PWD:s/\\/home\\/alice\\/secret//", "secret"},
	{"$PATH:s/:\\/opt\\/secret-bin//", "secret-bin"},
	{"$x\\\n:s/SECRET/", "SECRET"},
	{"$x:\\\ns/SECRET/", "SECRET"},
	{"$\\\nx:s/SECRET/", "SECRET"},
	{"$x:s/SECR\\\nET/", "SECRET"},
	{"\"$x:s/SE\\\nCRET/\"", "SECRET"},
	{"$x:s/SECRET/\\\n", "SECRET"},

	// A numeric glob inside a path in command position.
	{"/home/alice/<->/run SECRET", "alice"},
	{"/srv/acme-prod/<1-9>/deploy", "acme-prod"},
	{"/opt/customer-acme/<10-20>", "customer-acme"},
	{"A=1 /home/alice/<->/run", "alice"},
	{">f /home/alice/<->/run", "alice"},
	{"a/<1-5>/b", "a"},
	{"x/<->", "x"},
	{"bin<1-3>/tool", "bin"},
	{"dir<1->/x", "dir"},
	{"./build-<->/SECRETDIR/<->", "build-"},

	// A glob command word. Under EXTENDED_GLOB, `~` is exclusion and the word
	// after it is the pattern excluded, not the program.
	{"*/deploy~*/SECRET", "SECRET"},
	{"/usr/bin/*~/usr/bin/SECRET", "SECRET"},
	{"./bin/*~*/customer-acme", "customer-acme"},

	// More operator pieces split by a blank, a tab or a newline.
	{"> | grep hunter2 /etc/passwd", "hunter2"},
	{"> | tee /home/alice/secret.log", "secret.log"},
	{"> |ssh deploy@acme-prod.internal", "deploy@acme-prod.internal"},
	{"> & curl -H secret-token https://x", "-H"},
	{"> & rm -rf /srv/acme", "-rf"},
	{"> &git push SECRETREMOTE main", "push"},
	{"< & sort /home/alice/customer-list.csv", "customer-list.csv"},
	{">> | tee /home/alice/secret.log", "secret.log"},
	{">> & scp /home/alice/secret.csv host:", "secret.csv"},
	{"> \t| grep hunter2 f", "hunter2"},
	{">\t&\tgrep hunter2 f", "hunter2"},
	{"X=1 > | grep hunter2 f", "hunter2"},
	{"A=1 B=2 > & rm -rf /srv/acme", "-rf"},
	{"( > | grep hunter2 f )", "hunter2"},
	{"{ > | grep hunter2 f; }", "hunter2"},
	{"&& > | grep hunter2 f", "hunter2"},
	{">f > | grep hunter2 g", "hunter2"},
	{"> \\\n| grep hunter2 f", "hunter2"},
	{"> & | grep hunter2 f", "hunter2"},
	{">& | grep hunter2 f", "hunter2"},
	{">> & | grep hunter2 f", "hunter2"},
	{"&> | grep hunter2 f", "hunter2"},
	{"&>> | grep hunter2 f", "hunter2"},
	{"&> & grep hunter2 f", "hunter2"},
	{">\n|tee /home/alice/secret.log", "secret.log"},
	{">\n| grep hunter2 f", "hunter2"},
	{">\n&rm /srv/acme", "acme"},
	{">\n& curl -H secret-token x", "-H"},
	{"<\n&sort secret.csv", "secret.csv"},
	{">>\n|tee /home/alice/secret.log", "secret.log"},
	{"x=1 >\n|grep hunter2 f", "hunter2"},
	{"x=1 <\n&grep hunter2 f", "hunter2"},

	// A NUL, which truncates the line for every consumer that takes a C string.
	{"\x00#hunter2 ls", "\x00#hunter2"},
	{"X=1 \x00#hunter2 secret words", "\x00#hunter2"},
	{"\x00\x00#hunter2", "\x00\x00#hunter2"},
	{"; \x00#hunter2 arg", "\x00#hunter2"},
	{"{ \x00#hunter2; }", "\x00#hunter2"},
	{">\x00 /home/alice/secret.csv", "secret.csv"},
	{"<\x00 /home/alice/secret.csv sort", "secret.csv"},
	{">\x00 hunter2 cmd", "hunter2"},
	{"x=1 >\x00 hunter2 cmd", "hunter2"},
	{"<<<\x00 hunter2 cat", "hunter2"},
	{"&>\x00 hunter2 cmd", "hunter2"},

	// Function definitions: words followed by `()` define functions (zsh) or
	// are a syntax error (bash); the first name is never run. Here a
	// redirection, an expansion or a glob sits between the names, or a $'...'
	// the tokenizer misreads hides the `()` from it.
	{"deploy_acme >/dev/null deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme > /dev/null deploy_prod() { ls; }", "deploy_acme"},
	{"deploy_acme 2>/dev/null deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme >/dev/null 2>&1 deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme 2>x deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme <x deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme >&2 deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme &>x deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme >|x deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme <<<x deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme >x deploy_prod deploy_dev () { ls; }", "deploy_acme"},
	{"deploy_acme >x () { ls; }", "deploy_acme"},
	{"X=1 deploy_acme >x deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme >x deploy_prod ()\n{ ls; }", "deploy_acme"},
	{"deploy_acme > (x) deploy_prod () { ls; }", "deploy_acme"},
	{"deploy_acme $(echo x) () { ls; }", "deploy_acme"},
	{"deploy_acme $(date) () { ls; }", "deploy_acme"},
	{"deploy_acme $((1)) () { ls; }", "deploy_acme"},
	{"deploy_acme <(x) () { ls; }", "deploy_acme"},
	{"deploy_acme @(a) () { ls; }", "deploy_acme"},
	{"deploy_acme x(y) () { ls; }", "deploy_acme"},
	{"deploy_acme $'\\' ; ' () { ls; }", "deploy_acme"},
	{"deploy_acme $'\\' | ' () { ls; }", "deploy_acme"},
	{"deploy_acme $'\\' > ' () { ls; }", "deploy_acme"},
	{"deploy_acme $'\\'' () { ls; }", "deploy_acme"},
	{"deploy_acme deploy_prod $'x\\'' () { ls; }", "deploy_acme"},

	// Numeric globs and process substitutions again, in paths.
	{"~/.nvm/versions/node/v<18->/bin/node --version", "v"},
	{"/opt/acme-q<1-4>/bin/deploy --prod", "acme-q"},
	{"./releases/customer-acme<1-9>/run.sh", "customer-acme"},
	{"/opt/acme-q3-layoffs<(true) --run", "acme-q3-layoffs"},
	{"./customer-acme-export>(cat) --all", "customer-acme-export"},

	// Operator pieces again, and the here-string's `<<`+`<` split by a blank.
	{">\n& /home/alice/secret.csv SECRETARG", "SECRETARG"},
	{">\n| /home/alice/secret.csv SECRETARG", "SECRETARG"},
	{"> & /home/alice/secret.csv SECRETARG", "SECRETARG"},
	{"> | /home/alice/secret.csv SECRETARG", "SECRETARG"},
	{"<< <& secret-fd cmd", "secret-fd"},

	// Bytes the shell does not split on but a reader might: U+00A0 (the
	// artifact stored these two as 0x20; the claims say U+00A0, and only
	// that form reproduces the recorded value) and a vertical tab.
	{"git\u00a0push\u00a0origin\u00a0acme-secret-branch", "git\u00a0push\u00a0origin\u00a0acme-secret-branch"},
	{"cat\u00a0/Users/alice/customer-list.csv", "customer-list.csv"},
	{"cat\v/home/alice/secret.csv", "secret.csv"},
}

// commandWords are the programs these lines genuinely run, when they run one
// the search can find for certain.
var commandWords = map[string]bool{
	"ls": true, "sort": true, "open": true, "deploy": true, "cat": true, "cmd": true, "make": true, "echo": true, "grep": true,
	"wc": true, "xargs": true, "git": true, "gh": true, "npm": true, "kill": true,
	"jq": true, "read": true, "cd": true, "tee": true, "sed": true, "printf": true,
	"{": true, "[": true, "[[": true,
}

// TestNoCorpusLineLeaksIntoProgram: for every line in the corpus the program
// is null or a word that line runs as a command -- never a word from inside
// something the search did not parse. For every one of programClaims it is
// null: each claim was upheld as data, and none of those lines runs a command
// the search can find for certain -- so a value that happens to be a command
// word elsewhere (tee, cmd, cat) cannot come back on its own line either.
func TestNoCorpusLineLeaksIntoProgram(t *testing.T) {
	if len(leakCorpus) < 150 || len(programClaims) != 183 {
		t.Fatalf("premise broken: the corpus has %d lines and %d claims", len(leakCorpus), len(programClaims))
	}
	program := func(cmd string) *string {
		raw, err := json.Marshal(map[string]string{"command": cmd})
		if err != nil {
			t.Fatal(err)
		}
		return Derive("Bash", raw, []byte("key")).Program
	}
	for _, cmd := range leakCorpus {
		if got := program(cmd); got != nil && !commandWords[*got] {
			t.Errorf("program for %q is %q, a word from inside the line rather than its command", cmd, *got)
		}
	}
	for _, c := range programClaims {
		if got := program(c.in); got != nil {
			t.Errorf("program for %q is %q, want null (%q was recorded for it)", c.in, *got, c.program)
		}
	}
}
