package shape

import (
	"encoding/json"
	"testing"
)

// leakCorpus is every command line an adversarial review found to put data --
// an argument, a redirect target, a here-document or here-string word, an
// assignment value, an array element, an arithmetic operand, a fragment of a
// word the tokenizer split -- into the program field. The first 165 came from
// a review of the second version of the program search (54 of them leaked on
// main as well); the rest from a review of the third. Each is checked by a parser only; none is ever run.
var leakCorpus = []string{
	"\"$(< /etc/passwd)\"",
	"\"$(cat /etc/passwd)\"",
	"\"$(cat /home/alice/secret-path)\" --flag",
	"\"$(cat <<EOF\nhunter2\nEOF\n)\"",
	"\"$(echo $((a/b)))\"",
	"\"$(echo hello world)\"",
	"\"${(f)$(cat /a/b)}\"",
	"&& \"$(cat /x/y)\"",
	"&& arr[1 + 1]=x ls",
	"&>! /home/alice/secret.csv ls",
	"&>! file cmd",
	"&>>! log.txt echo hi",
	"( \"$(cat /x/secret-path)\" )",
	"( $[a/b] )",
	"( <<< ${x:-a b} cat )",
	"( >! out.log make )",
	"( X=\"$(echo \"a b\")\" ls )",
	"( arr[customer acme]=1 ls )",
	"( deploy_acme() { ls; }; deploy_acme )",
	"( n=$[a + b] )",
	"(2>&1 cmd)",
	"(arr[i==0]=v ls)",
	"(arr[k=/home/alice/x]=v ls)",
	"0<<<secret cat",
	"0<<EOF\nsecret body\nEOF",
	"10>log.txt cmd",
	"1>&2 echo error",
	"2>/dev/null ls",
	"2>/dev/null ls -la",
	"3<<<\"secret text\" cmd",
	"; \"$[a/b]\"",
	"; x=$'a\\' b c'",
	"< ${INPUT:?missing input file} cat",
	"< in \"$(cat /home/alice/secret.csv)\"",
	"<<< \"$(<\"/home/alice/My file.txt\")\" cat",
	"<<< \"$(cat \"a b\")\" grep y",
	"<<< \"$(echo \"a b\")\" cat",
	"<<< \"$(jq -r \".name\" \"/data/customer list.json\")\" xargs echo",
	"<<< $'don\\'t ; secret \"' cat",
	"<<< $'don\\'t SECRET here' cat",
	"<<< $[x * 3] cmd",
	"<<< ${msg:-hello world} cat",
	"<<< ${x:-a b c d} cmd",
	"<<< `echo a SECRET` wc -w",
	"<<< `printf %s secret word` cat",
	"<<< a >&! /tmp/out cat",
	"<<< x >! out cmd",
	"<<<`echo a b c` cat",
	"<<<x 2>&1 cmd",
	"> !(x) cmd",
	"> \"$( echo \"; secret\" )\" ls",
	"> \"$(dirname \"$HOME/My Documents/x\")/out\" cat",
	"> \"$(printf \"%s %s\" SECRET TWO)\" ls",
	"> \"$OUT_DIR/$(date \"+%Y-%m-%d %H\")\".log ls",
	"> #SECRET comment text\nls",
	"> $'\\' ; secret \"'",
	"> $'it\\'s a file' ls",
	"> $[1 + 2] cmd",
	"> ${HOME:-/tmp dir}/out.log cmd",
	"> ${OUT:?OUT must be set} make",
	"> ${arr[i + 1]} cmd",
	"> ${f// /_} ls",
	"> ${x#* } cmd",
	"> ${x%% *} cmd",
	"> ${x// /_} cmd",
	"> ${x: -1} cmd",
	"> ${x:-$[1 + 2]} cmd",
	"> ${x:-a b} cmd",
	"> ${x:-a b}${y:-c d} cmd",
	"> *(.) cmd",
	"> *(N) cmd",
	"> **/*(.om[1]) cmd",
	"> +(x) cmd",
	"> /dev/null 2>&1 command -v jq",
	"> /tmp/`date +%s %N`.log ls",
	"> ?(x y) cmd",
	"> @(a|b) cmd",
	"> `echo a b` cmd",
	"> `printf %s a b` ls",
	"> a${b:-c d}e cmd",
	"> f 0<<EOF",
	"> f 3<<<x cmd",
	"> f arr[i==0]=v ls",
	"> f { secret",
	"> file(1).txt cmd",
	"> out\rsecret ls",
	"> out; a[1 + 1]=x",
	">! /home/alice/secret.csv ls",
	">! file cmd",
	">\"$(date \"+%Y %m\")\" ls",
	">#c secret",
	">$[ a ] cmd",
	">&! /home/alice/secret.csv ls",
	">&! file cmd",
	">&${fd:-a b} cmd",
	">/dev/null 2>&1 cmd",
	">/dev/null 2>&1 command -v git",
	">>! /home/alice/secret.csv ls",
	">>! file cmd",
	">>&! /home/alice/secret.csv ls",
	">>&! file cmd",
	">f {fd}>g cmd",
	">out 2>err ls",
	">| ${x:-a b} cmd",
	"A=1 >! out.log make",
	"A=1 >f 2>f B=2 cmd",
	"A=1 {fd}>x cmd",
	"BRANCH=\"$(git log -1 --format=\"%s by %an\")\"",
	"COUNT=\"$(grep -c \"customer acme\" /data/x.csv)\" && echo $COUNT",
	"FOO=bar\rbaz qux",
	"GH_TOKEN=\"$(security find-generic-password -a \"$USER\" -s \"gh token\" -w)\" gh pr list",
	"JSON=\"$(curl -s -H \"Authorization: Bearer $TOKEN\" https://api.example.com)\"",
	"LATEST=\"$(ls -t \"/Users/alice/My Drive\" | head -1)\"",
	"MSG=\"$(printf \"%s %s\" SECRETA SECRETB)\" git commit -m \"$MSG\"",
	"NAME=\"${1:-\"default secret name\"}\" ./run.sh",
	"OUT=\"$(go test ./... 2>&1 | grep -v \"no test files\")\"",
	"PID=\"$(pgrep -f \"node server\")\" && kill $PID",
	"TS=\"$(date \"+%Y%m%d %H%M%S\")\"",
	"VERSION=\"$(cat \"my file.txt\")\" make",
	"VERSION=\"$(jq -r \".version // \\\"0.0.0\\\"\" package.json)\" npm publish",
	"X+=\"$(echo \"a b\")\" ls",
	"X=\"${Y//\"a b\"/c}\" ls",
	"X=$'\\'' echo 'SECRET words here'",
	"X=${arr[a b]} ls",
	"a[$(echo 1)]=v",
	"a[1 + 1]=x",
	"arr[$((i+1))]=v ls",
	"arr[0]=x \"$(cat /x)\"",
	"arr[a b]=SECRET ls",
	"arr[i==0]=secretvalue ls",
	"deploy_customer_acme() { echo hi; }; deploy_customer_acme",
	"f() { rm -rf /; }",
	"n=$[ 1 + 2 ] ls",
	"out=\"$(git log --format=\"%H %s\")\"",
	"x=\"$( echo \"; secret\" )\"",
	"x=\"$(echo \";secret\")\"",
	"x=\"$(echo \"a b\")\"",
	"x=\"$(echo \"a;b\")\"",
	"x=\"${a[$(echo \"1 2\")]}\" ls",
	"x=\"${y:-\"a b\"}\"",
	"x=\"${y:-\"| b\"}\"",
	"x=$'a\\' ; secret \"'",
	"x=$'a\\' b c' ls",
	"x=$'a\\' { secret \"'",
	"x=$'a\\' | secret \"'",
	"x=${y% *}",
	"x=${y:-default value}",
	"x=1\rsecret",
	"x=1 \r secret",
	"x=1 && FOO=$'it\\'s ; rm -rf x \"'",
	"x=1 { secret",
	"x=1; y=\"$(git log --format=\"%H %s\")\"",
	"y=${x// /_}",
	"{ 2>&1 cmd; }",
	"{ 2>&1 make; } | tee /tmp/build.log",
	"{ >! /home/alice/secret.csv ls; }",
	"{ >out 2>err ls; }",
	"{ x=$'a\\' ; secret \"'; }",
	"{ x=${y:-a b}; }",
	"{ { arr[x=1]=secret ls; }; }",
	"{customerfd}</home/alice/in.csv cat",
	"{fd}>/tmp/x echo hi",
	"{fd}>out ls",
	"| \"$(( a / b ))\"",
	"|| \"${x:-$(cat /etc/shadow)}\"",
	// A third review, against the version that ended at opaque words.
	"caf\u00e9=/Users/alice/acme-merger ls",
	"1=/home/alice/secret-path ls",
	"a[1]'='v ls",
	"X=$\\\n'it\\'s SECRET here' ls",
	"<\\\n<EOF\nsecret body\nEOF",
	"<1-9> /home/alice/secret.csv cat",
	"deploy_acme deploy_prod () { ls; }",
	"<\\\n<EOF\nhunter2 password\nEOF",
	"<\\\n<EOF\n/home/alice/.ssh/id_rsa\nEOF",
	"<\\\n<'EOF'\nSECRETBODY line\nEOF",
	"<\\\n<-EOF\n\tSECRETBODY\nEOF",
	"<\\\n<\\\n-EOF\nSECRETBODY\nEOF",
	"> /tmp/out <\\\n<EOF\nSECRETBODY hunter2\nEOF",
	"DB_PASS=x <\\\n<EOF\nSECRETBODY\nEOF",
	"A=1 >f <\\\n<EOF\nSECRETBODY\nEOF",
	"( <\\\n<EOF\nSECRETBODY\nEOF\n)",
	"{ <\\\n<EOF\nSECRETBODY\nEOF\n}",
	"X=$\\\n{Y:-a b c} cmd",
	"MSG=$\\\n{M:-deploy acme corp now} git push",
	"X=$\\\n'it\\'s secret words' cmd",
	"X=$\\\n'a\\' SECRET b' cmd",
	"X=$\\\n[1 + 2] cmd",
	"X=$\\\n[ 4111111111111111 ] cmd",
	"X=$\\\n{a[i + 1 + j]} cmd",
	"> $\\\n{x:-a b c} cmd",
	"<<< $\\\n{x:-alpha SECRET gamma} cat",
	"<<< $\\\n'don\\'t SECRET here' cat",
	"> $\\\n'it\\'s a file' ls",
	"( X=$\\\n{Y:-a b c} cmd )",
	"{ X=$\\\n{Y:-a b c} cmd; }",
	"> (x) cmd",
	"> (a|b) cmd",
	"> (/home/alice/secret.csv) ls",
	"< (secret.csv) cat",
	">> (build.log) make",
	">| (SECRET) make",
	">|(out.log) make",
	"&> (SECRET) make",
	"&>(SECRET) make",
	">& (SECRET) make",
	">&(SECRET) make",
	"<> (SECRET) cat",
	"<>(SECRET) cat",
	"<<< (SECRET) cat",
	">>| (SECRET) make",
	"> <1-10> cmd SECRET",
	"> <-> cmd SECRET",
	"<-> cmd SECRET",
	"<1-5> x SECRET",
	"A=1 <1-9> file secret",
	"< <-> cmd SECRET",
	"><1-5> cmd SECRET",
	"> f<1-3> cmd SECRET",
	"<<< <-> cat SECRET",
	">> <10-> tee SECRET",
	"( <-> a SECRET )",
	"{ <-> a SECRET; }",
	"<-5> ls SECRET",
	"<1-> ls SECRET",
	"a[0\\]=v customer_acme_q3 --prod",
	"MAP[key']'=secretvalue deploy --prod",
	"a[0\"]\"=v cmd SECRET",
	"a[0\\]+=v cmd SECRET",
	">f a[0\\]=v cmd SECRET",
	"A=1 a[k\\]=v cmd SECRET",
	"< (config|settings).json jq -r .name",
	"< (customer-list).csv wc -l",
	"> (secret-report).txt cat",
	"&>(acme-debug).log make",
	">|(acme-out).log make",
	"<<<(hunter2) cat",
	"A=1 < (secret|other).csv sort",
	"caf\u00e9=/Users/alice/Documents/secret.pdf open \"$caf\u00e9\"",
	"pr\u00e9nom=Alice ./greet.sh",
	"stra\u00dfe=/private/acme-merger.docx ls",
	"1=/home/alice/customer-list.csv ls",
	"2=hunter2 cmd",
	"1+=/private/secret-suffix ls",
	"x=1 1=/tmp/q3-layoffs.txt ls",
	"a[x]\"=\"v secret-arg",
	"a[x]'='/home/alice/secret.csv SECRETWORD",
	"a[x]\\=v SECRETWORD",
	"a[x]+\\=v SECRETWORD",
	"m[k]\"=\"hunter2 /home/alice/secret.csv",
	"cfg[env]\\=prod deploy-acme",
	"a[x\\]=v SECRETWORD",
	"a[x\"]\"=v SECRETWORD",
	"< report-<-> wc -l",
	"> f<-> cmd SECRETARG",
	"x=<-> SECRETCMD arg",
	"arr[0]\"=\"x SECRET",
	"arr[0]\\=x SECRET",
	"arr[0]'='x SECRET",
	"arr[0]\"+\"=x SECRET",
	"arr[0]\\+=x SECRET",
	"arr[0\"[\"]]=x SECRET",
	"arr[0\\]=x SECRET",
	"arr[0\"]\"=x SECRET",
	"arr['0]=x' SECRET",
	// A fourth: a redirect at the end of a line, whose "target" was the next
	// line's command.
	">\nrm -rf /home/alice/secret-dir",
	"<\ncat /home/alice/secret.csv",
	">\nscp /home/alice/secret.csv host:",
	"<\nsort /home/alice/customer-list.csv",
	"<<<\nmysql -phunter2 prod",
	">>\nssh deploy@acme-prod.internal",
	"> \t \ncat acme-merger.txt",
	">&\n2 SECRETWORD",
	"( <<<\ngit push SECRETREMOTE )",
	">\ncurl -H secret-token https://x",
	"&& >\nrm -rf /srv/acme",
	"A=1 B=2 >\nrm -rf /srv/acme",
	">f >\nrm -rf /srv/acme",
	"{ <\ncat /home/alice/secret.csv; }",
	">\\\n\nrm -rf x",
	">\n'rm' -rf x",
}

// commandWords are the programs these lines genuinely run, when they run one
// the search can find for certain.
var commandWords = map[string]bool{
	"ls": true, "sort": true, "open": true, "deploy": true, "cat": true, "cmd": true, "make": true, "echo": true, "grep": true,
	"wc": true, "xargs": true, "git": true, "gh": true, "npm": true, "kill": true,
	"jq": true, "read": true, "cd": true, "tee": true, "sed": true, "printf": true,
	"{": true, "[": true, "[[": true,
}

// TestNoCorpusLineLeaksIntoProgram: for every line in the corpus the program
// is null or a word that line runs as a command -- never a word from inside
// something the search did not parse.
func TestNoCorpusLineLeaksIntoProgram(t *testing.T) {
	if len(leakCorpus) < 150 {
		t.Fatalf("premise broken: the corpus has %d lines", len(leakCorpus))
	}
	for _, cmd := range leakCorpus {
		raw, err := json.Marshal(map[string]string{"command": cmd})
		if err != nil {
			t.Fatal(err)
		}
		got := Derive("Bash", raw, []byte("key"))
		if got.Program != nil && !commandWords[*got.Program] {
			t.Errorf("program for %q is %q, a word from inside the line rather than its command", cmd, *got.Program)
		}
	}
}
